[project]
name = "oaqjp-final-project-emb-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pylint>=3.3.7",
    "requests>=2.32.4",
    "ruff>=0.12.8",
]
